### ISSUE TITLE
Examples of use?

### ISSUE THREAD

**Issue by maelle** [gggodhwani/indian_village_boundaries#1]
I just wonder whether you've heard of examples of use for these data? E.g. visualization of census data or of data from data.gov.in?

**Comment by gggodhwani** [comment]
@masalmon Not much yet! I prepared this data for [DataKind Bangalore's project](http://www.datakind.org/blog/datakind-bangalore-datadive-to-datacorps) with our partner Digital Green, where we are using this data to do village profiling for building better recommendation of agricultural practices in rural communities.

**Comment by maelle** [comment]
Ok! Nice project! ☺
