### ISSUE TITLE
Unpacking .xz files

### ISSUE THREAD

**Issue by pjpaulpj** [gggodhwani/indian_village_boundaries#3]
Hey,

Thanks for your efforts to produce these maps.

When I try to unpack the file, it keeps producing other archive formats recursively? Am I doing something wrong?

Regards,

**Comment by gggodhwani** [comment]
Hey @pjpaulpj, what utility are you using to decompress? Would recommend: [xz-utils](https://tukaani.org/xz/)

**Comment by pjpaulpj** [comment]
That worked. Appreciate the response.
